name: Run Personal Finance Generator!

on: workflow_dispatch

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Run
        run: |
          pip install -r requirements.txt
          echo python personal_finance/run.py -y 2022 
          PYTHONPATH=. python personal_finance/run.py -y 2022 
        env:
          MINT_EMAIL: ${{ secrets.MINT_EMAIL }}
          MINT_PWD: ${{ secrets.MINT_PWD }}
          EMAIL_PWD: ${{ secrets.EMAIL_PWD }}
